gbp/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

# URLs Projeto
from projeto.views.atividade import AtividadeCreate, AtividadeDelete, AtividadeDetail, AtividadeList, AtividadeUpdate
from projeto.views.home import Permission, jBrowse, Location, Timeline
from projeto.views.instituicao import InstituicaoProjetoCreate, InstituicaoProjetoDelete, InstituicaoProjetoDetail, InstituicaoProjetoList, InstituicaoProjetoUpdate
from projeto.views.metaprojeto import MetaProjetoCreate, MetaProjetoDelete, MetaProjetoDetail, MetaProjetoList, MetaProjetoUpdate
from projeto.views.objetivo import ObjetivoProjetoCreate, ObjetivoProjetoDelete, ObjetivoProjetoDetail, ObjetivoProjetoList, ObjetivoProjetoUpdate
from projeto.views.palavrachave import PalavraChaveCreate, PalavraChaveDelete, PalavraChaveDetail, PalavraChaveList, PalavraChaveUpdate
from projeto.views.planoacao import PlanoAcaoCreate, PlanoAcaoDelete, PlanoAcaoDetail, PlanoAcaoList, PlanoAcaoUpdate
from projeto.views.projeto import ProjetoCreate, ProjetoDelete, ProjetoDetail, ProjetoList, ProjetoUpdate, ProjetoDashboard
from projeto.views.projetocomponente import ProjetoComponenteCreate, ProjetoComponenteDelete, ProjetoComponenteDetail, ProjetoComponenteList, ProjetoComponenteUpdate
from projeto.views.resultado import ResultadoProjetoCreate, ResultadoProjetoDelete, ResultadoProjetoDetail, ResultadoProjetoList, ResultadoProjetoUpdate
from projeto.views.tarefa import TarefaCreate, TarefaDelete, TarefaDetail, TarefaList, TarefaUpdate
from projeto.views import objetivo, resultado, projetocomponente, metaprojeto, planoacao, atividade, tarefa

# URLs Sequenciamento
from sequenciamento.views.sequenciamento import SequenciamentoCreate, SequenciamentoDelete, SequenciamentoDetail, SequenciamentoList, SequenciamentoUpdate
from sequenciamento.views.tarefasequenciamento import TarefaSequenciamentoCreate, TarefaSequenciamentoDelete, TarefaSequenciamentoDetail, TarefaSequenciamentoList, TarefaSequenciamentoUpdate
from sequenciamento.views.tiposequenciamento import TipoSequenciamentoCreate, TipoSequenciamentoDelete, TipoSequenciamentoDetail, TipoSequenciamentoList, TipoSequenciamentoUpdate
from sequenciamento.views.contrato import ContratoCreate, ContratoDelete, ContratoDetail, ContratoList, ContratoUpdate
from sequenciamento.views.dashboard import DashboardList

# URLs CMS
from cms.views import PaginaCreate, PaginaDelete, PaginaDetail, PaginaList, PaginaUpdate, PaginaContent

# URLs FDDB
from fddb.views import FddbCreate, FddbDelete, FddbDetail, FddbList, FddbUpdate, FddbDashBoard, FDDBAjax

# URLs Metabolomica
from metabolomica.views.sample import SampleCreate, SampleDelete, SampleDetail, SampleList, SampleUpdate
from metabolomica.views.approach import ApproachCreate, ApproachDelete, ApproachDetail, ApproachList, ApproachUpdate
from metabolomica.views.equipment import EquipmentCreate, EquipmentDelete, EquipmentDetail, EquipmentList, EquipmentUpdate
from metabolomica.views.result import ResultCreate, ResultDelete, ResultDetail, ResultList, ResultUpdate
from metabolomica.views.database import DatabaseCreate, DatabaseDelete, DatabaseDetail, DatabaseList, DatabaseUpdate
from metabolomica.views.dashboard import DashboardMetabolomica, DashboardApproachList, DashboardResultList, DashboardResultSampleList, DashboardDetail
from metabolomica.views.species import SpeciesCreate, SpeciesDelete, SpeciesDetail, SpeciesList, SpeciesUpdate
from metabolomica.views.formula import FormulaCreate, FormulaDelete, FormulaDetail, FormulaList, FormulaUpdate
from metabolomica.views.analytical import AnalyticalCreate, AnalyticalDelete, AnalyticalDetail, AnalyticalList, AnalyticalUpdate

# URLs ssRNAi
from ssrnai.views.dashboard import DashboardSsrnai
from ssrnai.views.percevejo.percevejo_database_serach import PercevejoDatabaseSearch
from ssrnai.views.percevejo.percevejo_results import PercevejoResults
from ssrnai.views.percevejo.percevejo_sequence import PercevejoSequence
from ssrnai.views.percevejo.percevejo_iscore import PercevejoIScore
from ssrnai.views.percevejo.percevejo_dicer import PercevejoDicer
from ssrnai.views.percevejo.percevejo_structure import PercevejoStructure
from ssrnai.views.percevejo.percevejo_expression import PercevejoExpression
from ssrnai.views.percevejo.percevejo_asiatico_expression import PercevejoAsiaticoExpression
from ssrnai.views.percevejo.percevejo_on_target import PercevejoOnTarget
from ssrnai.views.capim.capim_database_serach import CapimDatabaseSearch
from ssrnai.views.capim.capim_results import CapimResults
from ssrnai.views.capim.capim_sequence import CapimSequence
from ssrnai.views.capim.capim_iscore import CapimIScore
from ssrnai.views.capim.capim_dicer import CapimDicer
from ssrnai.views.capim.capim_structure import CapimStructure
from ssrnai.views.capim.capim_expression import CapimExpression
from ssrnai.views.capim.capim_on_target import CapimOnTarget
from ssrnai.views.buva.buva_database_serach import BuvaDatabaseSearch
from ssrnai.views.buva.buva_results import BuvaResults
from ssrnai.views.buva.buva_sequence import BuvaSequence
from ssrnai.views.buva.buva_iscore import BuvaIScore
from ssrnai.views.buva.buva_dicer import BuvaDicer
from ssrnai.views.buva.buva_structure import BuvaStructure
from ssrnai.views.buva.buva_expression import BuvaExpression
from ssrnai.views.buva.buva_canadensis_expression import BuvaCanadensisExpression
from ssrnai.views.buva.buva_on_target import BuvaOnTarget
from ssrnai.views.lagarta.lagarta_database_serach import LagartaDatabaseSearch
from ssrnai.views.lagarta.lagarta_results import LagartaResults
from ssrnai.views.lagarta.lagarta_sequence import LagartaSequence
from ssrnai.views.lagarta.lagarta_iscore import LagartaIScore
from ssrnai.views.lagarta.lagarta_dicer import LagartaDicer
from ssrnai.views.lagarta.lagarta_structure import LagartaStructure
from ssrnai.views.lagarta.lagarta_expression import LagartaExpression
from ssrnai.views.lagarta.lagarta_on_target import LagartaOnTarget
from ssrnai.views.nematoide.nematoide_database_serach import NematoideDatabaseSearch
from ssrnai.views.nematoide.nematoide_results import NematoideResults
from ssrnai.views.nematoide.nematoide_sequence import NematoideSequence
from ssrnai.views.nematoide.nematoide_iscore import NematoideIScore
from ssrnai.views.nematoide.nematoide_dicer import NematoideDicer
from ssrnai.views.nematoide.nematoide_structure import NematoideStructure
from ssrnai.views.nematoide.nematoide_expression import NematoideExpression
from ssrnai.views.nematoide.nematoide_on_target import NematoideOnTarget

urlpatterns = [

    # url(r'^$', Home.as_view(), name='home'),
    url(r'^$', PaginaContent.as_view(), {'pk': 5}, name='home'),
    url(r'^permission/$', Permission.as_view(), name='permission_denied'),

    # General Info about LBB
    url(r'^jbrowse/$', jBrowse.as_view(), name='jbrowse'),
    url(r'^location/$', Location.as_view(), name='location'),
    url(r'^timeline/$', Timeline.as_view(), name='timeline'),

    # Views de Projeto
    url(r'^projeto/new/$', ProjetoCreate.as_view(), name='new_projeto'),
    url(r'^projeto/list/', ProjetoList.as_view(), name='list_projeto'),
    url(r'^projeto/detail/(?P<pk>\d+)/$', ProjetoDetail.as_view(), name='detail_projeto'),
    url(r'^projeto/update/(?P<pk>\d+)/$', ProjetoUpdate.as_view(), name='update_projeto'),
    url(r'^projeto/delete/(?P<pk>\d+)/$', ProjetoDelete.as_view(), name='delete_projeto'),
    url(r'^projeto/dashboard/(?P<pk>\d+)/$', ProjetoDashboard.as_view(), name='dashboard_projeto'),

    # Views de Instituicao de Projeto
    url(r'^instituicao/$', InstituicaoProjetoList.as_view(),
        name='home_instituicao_projeto'),
    url(r'^instituicao/new/$', InstituicaoProjetoCreate.as_view(),
        name='new_instituicao_projeto'),
    url(r'^instituicao/list/', InstituicaoProjetoList.as_view(),
        name='list_instituicao_projeto'),
    url(r'^instituicao/detail/(?P<pk>\d+)/$',
        InstituicaoProjetoDetail.as_view(), name='detail_instituicao_projeto'),
    url(r'^instituicao/update/(?P<pk>\d+)/$',
        InstituicaoProjetoUpdate.as_view(), name='update_instituicao_projeto'),
    url(r'^instituicao/delete/(?P<pk>\d+)/$',
        InstituicaoProjetoDelete.as_view(), name='delete_instituicao_projeto'),

    # Views de Objetivo de Projeto
    url(r'^objetivo/$', ObjetivoProjetoList.as_view(),
        name='home_objetivo_projeto'),
    url(r'^objetivo/new/$', ObjetivoProjetoCreate.as_view(),
        name='new_objetivo_projeto'),
    url(r'^objetivo/list/projeto/(?P<pk>\d+)', ObjetivoProjetoList.as_view(),
        name='list_objetivo_projeto'),
    url(r'^objetivo/list/', ObjetivoProjetoList.as_view(),
        name='list_objetivo_projeto'),
    url(r'^objetivo/detail/(?P<pk>\d+)/$',
        ObjetivoProjetoDetail.as_view(), name='detail_objetivo_projeto'),
    url(r'^objetivo/update/(?P<pk>\d+)/$',
        ObjetivoProjetoUpdate.as_view(), name='update_objetivo_projeto'),
    url(r'^objetivo/delete/(?P<pk>\d+)/$',
        ObjetivoProjetoDelete.as_view(), name='delete_objetivo_projeto'),
    url(r'^objetivo/ajax/projeto/(?P<pk>\d+)$', objetivo.ObjetivosAjax, name='objetivos_ajax'),

    # Views de Resultado de Projeto
    url(r'^resultado/$', ResultadoProjetoList.as_view(),
        name='home_resultado_projeto'),
    url(r'^resultado/new/$', ResultadoProjetoCreate.as_view(),
        name='new_resultado_projeto'),
    url(r'^resultado/list/projeto/(?P<pk>\d+)', ResultadoProjetoList.as_view(),
        name='list_resultado_projeto'),
    url(r'^resultado/list/', ResultadoProjetoList.as_view(),
        name='list_resultado_projeto'),
    url(r'^resultado/detail/(?P<pk>\d+)/$',
        ResultadoProjetoDetail.as_view(), name='detail_resultado_projeto'),
    url(r'^resultado/update/(?P<pk>\d+)/$',
        ResultadoProjetoUpdate.as_view(), name='update_resultado_projeto'),

projeto/models/atividade.py
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils import timezone

from projeto.models.planoacao import PlanoAcao
from projeto.models.projeto import Projeto
from projeto.models.template import TemplateModelMixin

from smart_selects.db_fields import ChainedManyToManyField


#
# Atividade
#


class Atividade(models.Model, TemplateModelMixin):

    # Atributos
    numero = models.PositiveIntegerField(blank=True, default=1)
    nome = models.CharField(max_length=100, validators=[
                            MinLengthValidator(2)], blank=True)
    indicador_fisico = models.CharField(max_length=32, validators=[
                                        MinLengthValidator(2)], blank=True)
    peso_planoacao = models.PositiveIntegerField(blank=True, default=1)
    data_inicio = models.DateField(blank=True, default=timezone.now)
    data_fim = models.DateField(blank=True, default=timezone.now)

    # Relacionamentos
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE)

    planoacao = ChainedManyToManyField(
        PlanoAcao,
        chained_field="projeto",
        chained_model_field="projeto",
        auto_choose=True,
        blank=True,
    )

    responsavel = models.ForeignKey(
        User, null=True, blank=True, related_name='responsavel_atividade', on_delete=models.CASCADE)
    colaborador = models.ManyToManyField(
        User, blank=True, related_name='colaborador_atividade')

    data_cadastro = models.DateTimeField(auto_now_add=True, blank=True)
    data_atualizado = models.DateTimeField(auto_now=True, blank=True)
    criado_por = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['nome']
        verbose_name = 'atividade'
        verbose_name_plural = 'atividades'

    def __str__(self):
        return 'AT%d: %s' % (self.numero, self.nome)

projeto/models/metaprojeto.py
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.db import models

from projeto.models.objetivo import Objetivo
from projeto.models.projeto import Projeto
from projeto.models.template import TemplateModelMixin

from smart_selects.db_fields import ChainedManyToManyField


#
# Objetivo de Projetos
#

class MetaProjeto(models.Model, TemplateModelMixin):

    numero = models.IntegerField(default=1)
    nome = models.CharField(max_length=256, validators=[
                            MinLengthValidator(5)])
    projeto = models.ForeignKey(Projeto, on_delete=models.CASCADE)

    objetivo = ChainedManyToManyField(
        Objetivo,
        chained_field="projeto",
        chained_model_field="projeto",
        auto_choose=True,
        blank=True,
    )

    data_cadastro = models.DateTimeField(auto_now_add=True, blank=True)
    data_atualizado = models.DateTimeField(auto_now=True, blank=True)
    criado_por = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['nome']
        verbose_name = 'meta'
        verbose_name_plural = 'metas'

    def __str__(self):
        return 'MT%d: %s' % (self.numero, self.nome)

projeto/views/atividade.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView, ListView
from django.db.models import Q
from django.db.models import Count
from django.shortcuts import render

from projeto.forms import AtividadeForm
from projeto.models import Atividade, Projeto
from projeto.views.login import LoggedInMixin


def AtividadeAjax(request, pk):
    atividades = Atividade.objects.filter(projeto_id=int(pk)).order_by('numero')

    return render(request, 'atividades.html', {'atividades': atividades})


def AtividadePlanoAcaoAjax(request, pk):
    atividades = Atividade.objects.filter(planoacao_id=int(pk)).order_by('numero')

    return render(request, 'atividades.html', {'atividades': atividades})


class AtividadeList(LoggedInMixin, ListView):
    allowed_sort_fields = {'nome': {'default_direction': '', 'verbose_name': 'Nome'},
                           'data_atualizado': {'default_direction': '', 'verbose_name': 'Atualizado Em'}}

    default_sort_field = 'nome'
    paginate_by = 10

    template_name = 'atividade/crud/list.html'
    context_object_name = 'atividades'
    model = Atividade
    fields = '__all__'

    success_url = reverse_lazy('list_atividade_projeto')

    def get_queryset(self):
        if self.kwargs:
            queryset = self.model._default_manager.filter(projeto_id=int(self.kwargs['pk']))
        else:
            queryset = self.model._default_manager.all()

        return queryset

    def get_context_data(self, **kwargs):
        context = super(AtividadeList, self).get_context_data(**kwargs)
        context['projetos'] = Projeto.objects.all()
        context['projeto_id'] = 0

        if self.kwargs:
            context['projeto_id'] = self.kwargs['pk']

        return context


class AtividadeDetail(LoggedInMixin, DetailView):
    template_name = 'atividade/crud/detail.html'
    context_object_name = 'atividade'
    model = Atividade
    fields = '__all__'

    success_url = reverse_lazy('list_atividade_projeto')


class AtividadeCreate(LoggedInMixin, CreateView):
    template_name = 'atividade/crud/form.html'
    form_class = AtividadeForm

    def get_success_url(self):
        return reverse_lazy('detail_atividade_projeto', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.criado_por = self.request.user
        return super(AtividadeCreate, self).form_valid(form)

    def get_initial(self):
        try:
            return {'criado_por': self.request.user.id, 'numero': int(Atividade.objects.latest('data_atualizado').numero) + 1}
        except Atividade.DoesNotExist:
            return {'criado_por': self.request.user.id}

    def get_context_data(self, **kwargs):
        context = super(AtividadeCreate, self).get_context_data(**kwargs)
        context["projetos"] = Atividade.objects.values('projeto_id').annotate(total=Count('projeto_id')).order_by('projeto_id')

        return context

    def get_form_kwargs(self):
        if self.request.user.is_superuser:
            projetos = Projeto.objects.all()
        else:
            projetos = Projeto.objects.filter(Q(colaborador__in=[self.request.user.id]) | Q(criado_por=self.request.user.id) | Q(lider=self.request.user.id))

        kwargs = super(AtividadeCreate, self).get_form_kwargs()
        kwargs.update({'projetos': projetos})

        return kwargs


class AtividadeUpdate(LoggedInMixin, UpdateView):
    template_name = 'atividade/crud/form.html'
    form_class = AtividadeForm
    model = Atividade

    def get_success_url(self):
        return reverse_lazy('detail_atividade_projeto', kwargs={'pk': self.object.pk})

    def get_form_kwargs(self):
        if self.request.user.is_superuser:
            projetos = Projeto.objects.all()
        else:
            projetos = Projeto.objects.filter(Q(colaborador__in=[self.request.user.id]) | Q(criado_por=self.request.user.id) | Q(lider=self.request.user.id))

        kwargs = super(AtividadeUpdate, self).get_form_kwargs()
        kwargs.update({'projetos': projetos})

        return kwargs


class AtividadeDelete(LoggedInMixin, DeleteView):
    template_name = 'atividade/crud/delete.html'
    model = Atividade
    success_url = reverse_lazy('list_atividade_projeto')

projeto/views/home.py
from django.views.generic import TemplateView


class Home(TemplateView):
    template_name = "base/home.html"


class Permission(TemplateView):
    template_name = "base/permission.html"


class jBrowse(TemplateView):
    template_name = "base/content/jbrowse.html"


class Location(TemplateView):
    template_name = "base/content/location.html"


class Timeline(TemplateView):
    template_name = "base/content/timeline.html"

projeto/templates/objetivo/crud/delete.html
{% extends "base/base.html" %}

{% load bootstrap3 %}

{% block title %} <title>Apagar {{ object }}</title> {% endblock title %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    <h3>Deseja Apagar "{{ object }}"?</h3>

    <br/>

    {% buttons %}
        <button type="submit" class="btn btn-primary">Remover</button>
    {% endbuttons %}
</form>

{% endblock content %}

projeto/templates/objetivo/crud/detail.html
{% extends "base/base.html" %}

{% load bootstrap3 %}

{% block title %} <title>{{ objetivo }}</title> {% endblock title %}

{% block content %}

    {% include "base/menu-projetos.html" %} <br/>

    <h2>{{ objetivo }}</h2>

    <hr/>

    <p><b>Projeto:</b> <br/> <div class='text-highlight'><a href="{% url 'detail_projeto' objetivo.projeto.id %}">{{ objetivo.projeto }}</a>&nbsp;</div></p>

    <p><b>Descrição:</b> <br/> <div class='text-highlight'>{{ objetivo.descricao }}&nbsp;</div></p>

    <p><b>Cadastrado:</b> <br/> <div class='text-highlight'>{{ objetivo.data_cadastro   }}&nbsp;</div></p>

    <hr/>

    {% if request.user == objetivo.criado_por or request.user.is_superuser %}
      <p>
        <a href="{{ objetivo.get_update_url }}" class="btn btn-sm btn-warning">Editar</a>
        <a href="{{ objetivo.get_delete_url }}" class="btn btn-sm btn-danger">Apagar</a>
        <a href="{% url 'list_objetivo_projeto' %}" class="btn btn-sm btn-info">Voltar</a>
      </p>
    {% endif %}

{% endblock content %}

projeto/templates/objetivo/crud/form.html
{% extends "base/base.html" %}
{% load gbp_filters %}

{% load bootstrap3 %}

{% block title %} <title>Cadastrar/Editar Objetivo</title> {% endblock title %}

{% block content %}

    {% include "base/menu-projetos.html" %} <br/>

    <form class="form-horizontal" method="POST">
      {% if request.user|has_group:'Admin Projetos' or
            request.user|has_group:'Editor Projetos' or
            request.user.is_superuser %}
          {% csrf_token %}
          {% bootstrap_form form layout='horizontal' %}
          <div class="modal-footer">
              {% buttons %}
                 <button type="submit" class="btn btn-default btn-success">Enviar <span class="glyphicon glyphicon-ok"></span></button>
                 <a href="javascript:window.history.go(-1)" class="btn btn-default btn-info"><span class="glyphicon glyphicon-chevron-left"></span> Voltar</a>
                 <a href="{% url 'new_resultado_projeto' %}" class="btn btn-default btn-info">Próximo <span class="glyphicon glyphicon-chevron-right"></span></a>
              {% endbuttons %}
          </div>
        {% else %}
          <center><b>Você não possui permissão<b/></center>
        {% endif %}
    </form>

    {% if 'update' not in request.resolver_match.url_name %}
      <tbody class="objetivos">
         {% include 'objetivos.html' %}
      </tbody>
    {% endif %}

    <script>
      var value = {};

      {% for projeto in projetos %}
        value[{{projeto.projeto_id}}] = {{projeto.total}};
      {% endfor %}

      $(function() {
        if ($('#id_projeto').val() != 0) {
          $('#objetivos').html('').load("/objetivo/ajax/projeto/" + $('#id_projeto').val());
          $('#objetivos').show();
        }

        $('#id_projeto').on('change', function () {
          if ($(this).val() != 0) {
            if (value[$(this).val()]) {
              $('#objetivos').html('').load("/objetivo/ajax/projeto/" + $(this).val());
              $('#objetivos').show();
              $('#id_numero').val(value[$(this).val()] + 1);
            }
            else {
              $('#objetivos').hide();
              $('#id_numero').val(1);
            }
          }
          else {
            $('#objetivos').hide();
            $('#id_numero').val(1);
            $('#id_projeto').val("");
          }

          return false;
        });
      });
    </script>

{% endblock content %}

projeto/templates/objetivo/crud/list.html
{% extends "base/base.html" %}
{% load gbp_filters %}

{% load bootstrap3 %}

{% block title %} <title>Listar Objetivos de Projetos</title> {% endblock title %}

{% block content %}

    {% include "base/menu-projetos.html" %} <br/>

    <div style="min-width: 60%; float: right;">
      {% if request.user|has_group:'Admin Projetos' or request.user|has_group:'Editor Projetos' or request.user.is_superuser %}
        <div style="float: right;">
          <a href="{% url 'new_objetivo_projeto' %}" class="btn btn-sm btn-success">Adicionar</a>
        </div>
      {% endif %}

      <div style="float: left;">
        <div class="form-horizontal"><div class="form-group">
          <div class="col-md-12">
            <select id="listar_projeto" class="form-control" name="listar_projeto" onChange="redirectUrl()">
              <option value="0">Todos os Projetos</option>
              {% for projeto in projetos %}
                <option value="{{projeto.id}}">{{projeto}}</option>
              {% endfor %}
            </select>
          </div>
        </div></div>
      </div>
    </div>
    <br/><br/>

    {% if not objetivos %}

      <div class="jumbotron"><h4>Nenhum Dado Cadastrado.</h4></div>

    {% else %}

        {% include 'base/sort_links.html' %}

        {% for objetivo in objetivos %}
            <ul class="list-group">
              <li class="list-group-item">

                <h3><a href="{{ objetivo.get_detail_url }}">{{ objetivo }} - {{ objetivo.projeto }}</a></h3>

                <p><b>Descrição:</b> <br/> <div class='text-highlight'>{{ objetivo.descricao }}&nbsp;</div></p>

                <br/>
                {% if request.user == objetivo.criado_por or request.user.is_superuser %}
                  <p>
                    <a href="{{ objetivo.get_update_url }}" class="btn btn-sm btn-warning">Editar</a>
                    <a href="{{ objetivo.get_delete_url }}" class="btn btn-sm btn-danger">Apagar</a>
                  </p>
                {% endif %}

                <div class="data-atualizado">{{ objetivo.data_atualizado }}</div>

              </li>
            </ul>
        {% endfor %}

        {% include 'base/pagination.html' %}

    {% endif %}

    <script>
        $(function(){
          $('#listar_projeto').val({{projeto_id}});

          $('#listar_projeto').on('change', function () {

          if ($(this).val() != 0) {
            var url = '/objetivo/list/projeto/' + $(this).val();

            if (url) {
              window.location = url;
            }
          }
          else {
            window.location = '{% url 'list_objetivo_projeto' %}';
          }

          return false;
        });
      });
    </script>

{% endblock content %}